### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [Diana-Doe/homework#1]
Чи добре я розумію, що Ви хочете взяти з сайту інформацію про всі продукти та зробити веб застосунок де буде ця інформація представлена? Потрібно виправити помилки в тексті 'заранити' 'приємлимі' та подібні.

Тема: Аналіз популярності пристроїв "Розумний будинок".

**Comment by Diana-Doe** [comment]
Так. 
Добре, весь сленг буде виправленим 😓
